name: Run Selenium Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      BASE_API_URL: ${{ vars.BASE_API_URL }}
      USER_EMAIL: ${{ vars.USER_EMAIL }}
      USERNAME: ${{ vars.USERNAME }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Install dependencies
        run: npm install

      - name: Install Chrome browser
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE)
          curl -sSLO https://storage.googleapis.com/chrome-for-testing-public/${CHROME_DRIVER_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium tests
        run: npm run test
          
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
  
    steps:
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
          name: test-artifact
          path: ./failedScreenshots
  
