name: Run Selenium Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      BASE_API_URL: ${{ vars.BASE_API_URL }}
      USER_EMAIL: ${{ vars.USER_EMAIL }}
      USERNAME: ${{ vars.USERNAME }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Install dependencies
        run: npm install

      - name: Install Chrome browser
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE)
          curl -sSLO https://storage.googleapis.com/chrome-for-testing-public/${CHROME_DRIVER_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium tests
        run: npm run test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          
      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: ./failedScreenshots
  
